name: kiko_getx_xmshop
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter_screenutil: ^5.5.4 #适配
  flutter_swiper_view: ^1.1.8 #轮播图
  dio: ^4.0.6 #网络请求
  flutter_staggered_grid_view: ^0.6.2 #瀑布流
  shared_preferences: ^2.0.15 #本地历史记录
  flutter_html: ^3.0.0-alpha.6 #html
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  fonts:
    - family: MyIcon   #指定一个字体名 根据自己的需求定义
      fonts:
        - asset: assets/fonts/iconfont.ttf 
  assets:
    - assets/images/xiaomiBanner.png
    - assets/images/2.0x/xiaomiBanner.png
    - assets/images/3.0x/xiaomiBanner.png
    - assets/images/xiaomiBanner2.png
    - assets/images/2.0x/xiaomiBanner2.png
    - assets/images/3.0x/xiaomiBanner2.png
    - assets/images/hot_search.png
    - assets/images/2.0x/hot_search.png
    - assets/images/3.0x/hot_search.png 
    - assets/images/service.png
    - assets/images/2.0x/service.png
    - assets/images/3.0x/service.png
    - assets/images/user.png
    - assets/images/2.0x/user.png
    - assets/images/3.0x/user.png
    - assets/images/user_ad1.png
    - assets/images/2.0x/user_ad1.png
    - assets/images/3.0x/user_ad1.png    
    - assets/images/user_ad2.png
    - assets/images/2.0x/user_ad2.png
    - assets/images/3.0x/user_ad2.png    
    